'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type LanguageCode = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'kn' | 'es'

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string) => string
}

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'mr', name: 'मराठी' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'es', name: 'Español' }
]

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navbar & Layout
    home: 'Home',
    features: 'Features',
    dashboard: 'Dashboard',
    about: 'About',
    contact: 'Contact',
    sosButton: 'Emergency SOS',
    login: 'Login',
    signUp: 'Sign Up',
    govtInitiative: 'Government of India Initiative',
    ministryLabel: 'Ministry of Road Transport and Highways',
    helplineTitle: 'National Emergency Toll-Free Helplines',
    policeHelpline: 'Police',
    ambulanceHelpline: 'Ambulance',
    highwayHelpline: 'National Highway Authority',
    disasterHelpline: 'Disaster Management',

    // Hero Section
    heroTitle: 'Every Second Saves a Life.',
    heroSubtitle: 'AI-Powered Emergency Response System for Road Accidents. Reducing response time during the Golden Hour.',
    tryAI: 'Try AI Assistant',
    watchDemo: 'Watch Demo',

    // SOS Flow
    sosFlowTitle: 'Emergency SOS Flow',
    sosFlowSubtitle: 'One-tap activation triggers a complete emergency response sequence',
    sosStep1Title: 'Trigger SOS Alert',
    sosStep1Desc: 'One-tap SOS button immediately captures precise GPS coordinates and medical profiles.',
    sosStep2Title: 'SMS & Contact Broadcast',
    sosStep2Desc: 'Dispatches emergency SMS alerts with live map links to family and registered guardians.',
    sosStep3Title: 'Ambulance Dispatch',
    sosStep3Desc: 'Coordinates with nearest trauma hospitals, dispatching paramedics using smart routing.',
    sosStep4Title: 'Live Dispatch Map',
    sosStep4Desc: 'Displays real-time routing navigation for incoming medical vehicles.',

    // About Section
    aboutTitle: 'About RoadSOS AI',
    aboutSubtitle: 'RoadSOS AI is a Government of India initiative to leverage artificial intelligence for road safety and emergency response. Our platform connects accident victims with emergency services within the critical Golden Hour, significantly improving survival rates.',
    value1Title: 'Safety First',
    value1Desc: 'Every feature designed with user safety as the top priority.',
    value2Title: 'Save Lives',
    value2Desc: 'Our mission is to reduce road accident fatalities across India.',
    value3Title: 'Lightning Fast',
    value3Desc: 'Average response time of just 7 minutes during emergencies.',
    value4Title: 'Community Driven',
    value4Desc: 'Built by the community, for the community.',
    impactTitle: 'Our Impact',
    livesSaved: 'Lives Saved',
    hospitals: 'Trauma Centers',
    ambulances: 'Connected Ambulances',
    cities: 'Smart Cities',

    // Contact Section
    contactTitle: 'Contact Us',
    contactSubtitle: 'Have questions? We are here to help 24/7',
    email: 'Email',
    emergency: 'Emergency Helpline',
    address: 'Address',
    addressVal: 'Digital India Centre, New Delhi',
    nameLabel: 'Name',
    emailLabel: 'Email',
    messageLabel: 'Message',
    sendBtn: 'Send Message',

    // First Aid Section
    firstAidTitle: 'First Aid Guidance',
    firstAidSubtitle: 'Interactive instructions and CPR support during emergencies',
    cprTitle: 'Cardiopulmonary Resuscitation (CPR)',
    cprDesc: 'Guide for bystanders to keep blood circulating until paramedics arrive.',
    cprStep1: 'Place hands in the center of the chest.',
    cprStep2: 'Push hard and fast at a rate of 100-120 compressions per minute.',
    cprStep3: 'Follow the metronome pace below.',
    metronomeBtnStart: 'Start CPR Metronome (110 BPM)',
    metronomeBtnStop: 'Stop CPR Metronome',
    bleedingTitle: 'Bleeding Management',
    bleedingDesc: 'Immediate steps to control severe hemorrhaging.',
    bleedingStep1: 'Apply direct pressure with a clean cloth or bandage.',
    bleedingStep2: 'Elevate the wound above heart level if possible.',
    bleedingStep3: 'Maintain pressure; do not remove the cloth if soaked.',

    // Live Map Section
    mapTitle: 'Live Emergency Map',
    mapSubtitle: 'Real-time grid showing nearby trauma centers and ambulance dispatches',
    satelliteMode: 'Satellite Map View',
    vectorMode: 'Standard Vector Map',
    searchServicePlaceholder: 'Search hospitals or ambulances...',
    dispatchAmbulanceBtn: 'Simulate Dispatch Route',
    hospitalLabel: 'Trauma Hospital',
    ambulanceLabel: 'Paramedic Ambulance',
    policeLabel: 'Highway Patrol Squad',
    activeHazards: 'Road Hazard Closures',
    reportIncidentBtn: 'File Road Incident Report',
    loginToReportMsg: 'Please log in to submit road emergency incident files directly to dispatchers.',

    // Dashboard Section
    dashboardTitle: 'Citizen Control Center',
    dashboardSubtitle: 'Manage medical information, emergency contacts, and active dispatches',
    profileSaved: 'Medical Profile Saved Successfully',
    bloodGroup: 'Blood Group',
    allergies: 'Allergies & Contraindications',
    emergencyContacts: 'Emergency Contacts',
    addContact: 'Add Contact Name/Number',
    droneTitle: 'Patrol Drone Telemetry (Digital Twin)',
    droneAltitude: 'Altitude',
    droneBattery: 'Battery',
    droneSatelites: 'GPS Satellites Connected',

    // Chatbot Section
    chatbotTitle: 'Sarthi - AI Gov Helpdesk',
    chatbotWelcome: 'Greetings. I am Sarthi, your official Road Safety AI Guide. State your emergency or query.',
    chatbotPrompt: 'Ask Sarthi (e.g. "How to treat a burn?", "Hospital coordinates")',
    analysisHeader: 'AI Collision Damage Analysis Report',
    severityLabel: 'Damage Severity Level',
    detectedHazardsLabel: 'Identified Hazards',
    recommendationsLabel: 'Recommended Actions'
  },
  hi: {
    // Navbar & Layout
    home: 'मुख्य पृष्ठ',
    features: 'विशेषताएं',
    dashboard: 'डैशबोर्ड',
    about: 'हमारे बारे में',
    contact: 'संपर्क',
    sosButton: 'आपातकालीन एसओएस',
    login: 'लॉगिन',
    signUp: 'साइन अप',
    govtInitiative: 'भारत सरकार की पहल',
    ministryLabel: 'सड़क परिवहन और राजमार्ग मंत्रालय',
    helplineTitle: 'राष्ट्रीय आपातकालीन टोल-फ्री हेल्पलाइन',
    policeHelpline: 'पुलिस',
    ambulanceHelpline: 'एम्बुलेंस',
    highwayHelpline: 'राष्ट्रीय राजमार्ग प्राधिकरण',
    disasterHelpline: 'आपदा प्रबंधन',

    // Hero Section
    heroTitle: 'हर सेकंड एक जीवन बचाता है।',
    heroSubtitle: 'सड़क दुर्घटनाओं के लिए एआई-संचालित आपातकालीन प्रतिक्रिया प्रणाली। स्वर्णिम घंटे (Golden Hour) के दौरान प्रतिक्रिया समय को कम करना।',
    tryAI: 'एआई सहायक आज़माएं',
    watchDemo: 'डेमो देखें',

    // SOS Flow
    sosFlowTitle: 'आपातकालीन एसओएस प्रवाह',
    sosFlowSubtitle: 'एक-टैप सक्रियण एक पूर्ण आपातकालीन प्रतिक्रिया अनुक्रम को ट्रिगर करता है',
    sosStep1Title: 'एसओएस अलर्ट शुरू करें',
    sosStep1Desc: 'एक-टैप एसओएस बटन तुरंत सटीक जीपीएस निर्देशांक और चिकित्सा प्रोफ़ाइल कैप्चर करता है।',
    sosStep2Title: 'एसएमएस और संपर्क प्रसारण',
    sosStep2Desc: 'परिवार और पंजीकृत अभिभावकों को लाइव मैप लिंक के साथ आपातकालीन एसएमएस अलर्ट भेजता है।',
    sosStep3Title: 'एम्बुलेंस प्रेषण',
    sosStep3Desc: 'निकटतम आघात अस्पतालों के साथ समन्वय करता है, स्मार्ट रूटिंग का उपयोग करके पैरामेडिक्स को भेजता है।',
    sosStep4Title: 'लाइव प्रेषण मानचित्र',
    sosStep4Desc: 'आने वाले आपातकालीन वाहनों के लिए रीयल-टाइम मार्ग नेविगेशन प्रदर्शित करता है।',

    // About Section
    aboutTitle: 'सड़क सुरक्षा एआई के बारे में',
    aboutSubtitle: 'RoadSOS AI सड़क सुरक्षा और आपातकालीन प्रतिक्रिया के लिए कृत्रिम बुद्धिमत्ता (AI) का लाभ उठाने के लिए भारत सरकार की एक पहल है। हमारा मंच दुर्घटना पीड़ितों को महत्वपूर्ण स्वर्णिम घंटे (Golden Hour) के भीतर आपातकालीन सेवाओं से जोड़ता है, जिससे जीवन रक्षा दर में काफी सुधार होता है।',
    value1Title: 'सुरक्षा सर्वोपरि',
    value1Desc: 'उपयोगकर्ता सुरक्षा को सर्वोच्च प्राथमिकता के रूप में रखकर डिज़ाइन की गई हर सुविधा।',
    value2Title: 'जीवन बचाएं',
    value2Desc: 'हमारा मिशन पूरे भारत में सड़क दुर्घटना में होने वाली मौतों को कम करना है।',
    value3Title: 'बिजली जैसी गति',
    value3Desc: 'आपात स्थिति के दौरान केवल 7 मिनट का औसत प्रतिक्रिया समय।',
    value4Title: 'समुदाय संचालित',
    value4Desc: 'समुदाय द्वारा, समुदाय के लिए निर्मित।',
    impactTitle: 'हमारा प्रभाव',
    livesSaved: 'बचाए गए जीवन',
    hospitals: 'आघात केंद्र',
    ambulances: 'संबद्ध एम्बुलेंस',
    cities: 'स्मार्ट शहर',

    // Contact Section
    contactTitle: 'संपर्क करें',
    contactSubtitle: 'कोई सवाल है? हम आपकी सहायता के लिए 24/7 यहां उपलब्ध हैं',
    email: 'ईमेल',
    emergency: 'आपातकालीन हेल्पलाइन',
    address: 'पता',
    addressVal: 'डिजिटल इंडिया सेंटर, नई दिल्ली',
    nameLabel: 'नाम',
    emailLabel: 'ईमेल पता',
    messageLabel: 'संदेश',
    sendBtn: 'संदेश भेजें',

    // First Aid Section
    firstAidTitle: 'प्राथमिक उपचार मार्गदर्शन',
    firstAidSubtitle: 'आपात स्थिति के दौरान इंटरैक्टिव निर्देश और सीपीआर सहायता',
    cprTitle: 'कार्डियोपल्मोनरी रिससिटेशन (सीपीआर)',
    cprDesc: 'पैरामेडिक्स के आने तक रक्त परिसंचरण बनाए रखने के लिए मार्गदर्शन।',
    cprStep1: 'हाथों को छाती के बीच में रखें।',
    cprStep2: 'प्रति मिनट 100-120 कंप्रेस की दर से तेजी से और जोर से दबाएं।',
    cprStep3: 'नीचे दिए गए मेट्रोनोम गति का पालन करें।',
    metronomeBtnStart: 'सीपीआर मेट्रोनोम प्रारंभ करें (110 BPM)',
    metronomeBtnStop: 'सीपीआर मेट्रोनोम बंद करें',
    bleedingTitle: 'रक्तस्राव प्रबंधन',
    bleedingDesc: 'गंभीर रक्तस्राव को नियंत्रित करने के लिए तत्काल कदम।',
    bleedingStep1: 'साफ कपड़े या पट्टी से सीधे दबाव डालें।',
    bleedingStep2: 'यदि संभव हो तो घाव को हृदय स्तर से ऊपर उठाएं।',
    bleedingStep3: 'दबाव बनाए रखें; यदि कपड़ा भीग गया हो तो उसे न हटाएं।',

    // Live Map Section
    mapTitle: 'लाइव आपातकालीन मानचित्र',
    mapSubtitle: 'निकटतम आघात केंद्रों और एम्बुलेंस प्रेषण को दिखाने वाला वास्तविक समय ग्रिड',
    satelliteMode: 'सैटेलाइट मानचित्र व्यू',
    vectorMode: 'मानक मानचित्र व्यू',
    searchServicePlaceholder: 'अस्पतालों या एम्बुलेंसों की खोज करें...',
    dispatchAmbulanceBtn: 'प्रेषण सिमुलेशन प्रारंभ करें',
    hospitalLabel: 'आघात अस्पताल',
    ambulanceLabel: 'पैरामेडिक एम्बुलेंस',
    policeLabel: 'राजमार्ग गश्ती दल',
    activeHazards: 'सड़क मार्ग बंद (बाधाएं)',
    reportIncidentBtn: 'सड़क दुर्घटना की रिपोर्ट दर्ज करें',
    loginToReportMsg: 'आपातकालीन प्रेषणकर्ताओं को सीधे सड़क दुर्घटना रिपोर्ट जमा करने के लिए कृपया लॉगिन करें।',

    // Dashboard Section
    dashboardTitle: 'नागरिक नियंत्रण केंद्र',
    dashboardSubtitle: 'अपनी चिकित्सा जानकारी, आपातकालीन संपर्क और सक्रिय एम्बुलेंस ट्रैक करें',
    profileSaved: 'चिकित्सा प्रोफ़ाइल सफलतापूर्वक सहेजी गई',
    bloodGroup: 'रक्त समूह',
    allergies: 'एलर्जी और अन्य समस्याएं',
    emergencyContacts: 'आपातकालीन संपर्क',
    addContact: 'नया आपातकालीन संपर्क जोड़ें (नाम/नंबर)',
    droneTitle: 'ड्रोन टेलीमेट्री (डिजिटल ट्विन)',
    droneAltitude: 'ऊंचाई',
    droneBattery: 'बैटरी क्षमता',
    droneSatelites: 'सक्रिय जीपीएस उपग्रह जुड़े हुए हैं',

    // Chatbot Section
    chatbotTitle: 'सार्थी - एआई सरकारी हेल्पडेस्क',
    chatbotWelcome: 'नमस्कार। मैं सार्थी हूँ, आपकी आधिकारिक सड़क सुरक्षा एआई गाइड। अपनी आपातकालीन स्थिति या प्रश्न दर्ज करें।',
    chatbotPrompt: 'सार्थी से पूछें (उदा. "जलने का इलाज कैसे करें?", "अस्पताल का पता")',
    analysisHeader: 'एआई दुर्घटना विश्लेषण रिपोर्ट',
    severityLabel: 'क्षति की गंभीरता स्तर',
    detectedHazardsLabel: 'पहचाने गए खतरे',
    recommendationsLabel: 'अनुशंसित कार्रवाइयां'
  },
  mr: {
    home: 'मुख्य पान',
    features: 'वैशिष्ट्ये',
    dashboard: 'डॅशबोर्ड',
    about: 'आमच्याबद्दल',
    contact: 'संपर्क',
    sosButton: 'आणीबाणी SOS',
    login: 'लॉगिन',
    signUp: 'साइन अप',
    govtInitiative: 'भारत सरकारचा पुढाकार',
    ministryLabel: 'रस्ते वाहतूक आणि महामार्ग मंत्रालय',
    helplineTitle: 'राष्ट्रीय आपत्कालीन टोल-फ्री हेल्पलाइन',
    policeHelpline: 'पोलीस',
    ambulanceHelpline: 'रुग्णवाहिका',
    highwayHelpline: 'राष्ट्रीय महामार्ग प्राधिकरण',
    disasterHelpline: 'आपत्ती व्यवस्थापन',
    heroTitle: 'प्रत्येक सेकंद एक जीव वाचवतो.',
    heroSubtitle: 'रस्ते अपघातांसाठी एआय-आधारित आपत्कालीन प्रतिसाद प्रणाली. सुवर्ण तासादरम्यान (Golden Hour) प्रतिसाद वेळ कमी करणे.',
    tryAI: 'एआय सहाय्यक वापरा',
    watchDemo: 'डेमो पहा',
    sosFlowTitle: 'आपत्कालीन एसओएस प्रवाह',
    sosFlowSubtitle: 'एक-टॅप क्रिया संपूर्ण आपत्कालीन प्रतिसाद प्रक्रिया सुरू करते',
    sosStep1Title: 'एसओएस अलर्ट सुरू करा',
    sosStep1Desc: 'एक-टॅप एसओएस बटण त्वरित अचूक जीपीएस समन्वय आणि वैद्यकीय प्रोफाइल हस्तगत करते.',
    sosStep2Title: 'एसएमएस आणि संपर्क ब्रॉडकास्ट',
    sosStep2Desc: 'कुटुंब आणि नोंदणीकृत पालकांना लाइव्ह मॅप लिंकसह आपत्कालीन एसएमएस अलर्ट पाठवतो.',
    sosStep3Title: 'रुग्णवाहिका प्रेषण',
    sosStep3Desc: 'जवळच्या ट्रामा हॉस्पिटल्सशी समन्वय साधतो, स्मार्ट रूटिंग वापरून पॅरामेडिक्स पाठवतो.',
    sosStep4Title: 'लाइव्ह प्रेषण नकाशा',
    sosStep4Desc: 'येणाऱ्या आपत्कालीन वाहनांसाठी रिअल-टाइम मार्ग नेव्हिगेशन दाखवतो.',
    aboutTitle: 'रस्ते सुरक्षा एआयबद्दल',
    aboutSubtitle: 'RoadSOS AI हा रस्ते सुरक्षा आणि आपत्कालीन प्रतिसादासाठी कृत्रिम बुद्धिमत्ता (AI) वापरण्यासाठी भारत सरकारचा एक उपक्रम आहे. आमचा प्लॅटफॉर्म अपघातातील बळींना महत्त्वाच्या सुवर्ण तासात (Golden Hour) आपत्कालीन सेवांशी जोडतो, ज्यामुळे जीवन जगण्याचे प्रमाण लक्षणीयरीत्या सुधारते.',
    value1Title: 'सुरक्षा प्रथम',
    value1Desc: 'वापरकर्ता सुरक्षिततेला सर्वोच्च प्राधान्य देऊन डिझाइन केलेले प्रत्येक वैशिष्ट्य.',
    value2Title: 'जीव वाचवा',
    value2Desc: 'संपूर्ण भारतात रस्ते अपघातातील मृत्यू कमी करणे हे आमचे ध्येय आहे.',
    value3Title: 'वेगवान वेग',
    value3Desc: 'आणीबाणीच्या काळात फक्त ७ मिनिटांचा सरासरी प्रतिसाद वेळ.',
    value4Title: 'समुदाय संचलित',
    value4Desc: 'समुदायाद्वारे, समुदायासाठी तयार केलेले.',
    impactTitle: 'आमचा प्रभाव',
    livesSaved: 'वाचवलेले जीव',
    hospitals: 'ट्रामा केअर सेंटर्स',
    ambulances: 'संबद्ध रुग्णवाहिका',
    cities: 'स्मार्ट शहरे',
    contactTitle: 'संपर्क करा',
    contactSubtitle: 'काही प्रश्न आहेत? आम्ही तुम्हाला २४/७ मदत करण्यासाठी येथे आहोत',
    email: 'ईमेल',
    emergency: 'आपत्कालीन हेल्पलाइन',
    address: 'पत्ता',
    addressVal: 'डिजिटल इंडिया सेंटर, नवी दिल्ली',
    nameLabel: 'नाव',
    emailLabel: 'ईमेल पत्ता',
    messageLabel: 'संदेश',
    sendBtn: 'संदेश पाठवा',
    firstAidTitle: 'प्रथमोपचार मार्गदर्शन',
    firstAidSubtitle: 'आपत्कालीन परिस्थितीत परस्परसंवादी सूचना आणि सीपीआर सहाय्य',
    cprTitle: 'सीपीआर (CPR)',
    cprDesc: 'पॅरामेडिक्स येईपर्यंत रक्ताभिसरण चालू ठेवण्यासाठी मार्गदर्शन.',
    cprStep1: 'हात छातीच्या मध्यभागी ठेवा.',
    cprStep2: 'प्रति मिनिट १००-१२० वेळा दाबण्याच्या गतीने वेगाने दाबा.',
    cprStep3: 'खालील मेट्रोनोम गतीचे अनुसरण करा.',
    metronomeBtnStart: 'सीपीआर मेट्रोनोम सुरू करा',
    metronomeBtnStop: 'सीपीआर मेट्रोनोम बंद करा',
    bleedingTitle: 'रक्तस्त्राव नियंत्रण',
    bleedingDesc: 'गंभीर रक्तस्त्राव रोखण्यासाठी त्वरित पावले.',
    bleedingStep1: 'स्वच्छ कापडाने थेट जखमेवर दाब द्या.',
    bleedingStep2: 'शक्य असल्यास अवयव हृदयाच्या पातळीपेक्षा उंच करा.',
    bleedingStep3: 'दाब कायम ठेवा; कापड रक्ताने भिजले तरी काढू नका.',
    mapTitle: 'लाइव्ह आपत्कालीन नकाशा',
    mapSubtitle: 'जवळचे ट्रामा केअर सेंटर्स आणि रुग्णवाहिका दर्शवणारा रिअल-टाइम ग्रिड',
    satelliteMode: 'सॅटेलाइट मॅप व्ह्यू',
    vectorMode: 'मानक मॅप व्ह्यू',
    searchServicePlaceholder: 'हॉस्पिटल्स किंवा रुग्णवाहिका शोधा...',
    dispatchAmbulanceBtn: 'सिम्युलेशन सुरू करा',
    hospitalLabel: 'हॉस्पिटल',
    ambulanceLabel: 'रुग्णवाहिका',
    policeLabel: 'महामार्ग गस्त',
    activeHazards: 'रस्ता अडथळे',
    reportIncidentBtn: 'अपघाताचा अहवाल द्या',
    loginToReportMsg: 'आपत्कालीन प्रेषणकर्त्यांना थेट अहवाल पाठवण्यासाठी कृपया लॉगिन करा.',
    dashboardTitle: 'नागरिक नियंत्रण केंद्र',
    dashboardSubtitle: 'वैद्यकीय माहिती, आपत्कालीन संपर्क आणि सक्रिय रुग्णवाहिका व्यवस्थापित करा',
    profileSaved: 'वैद्यकीय प्रोफाइल यशस्वीरित्या जतन केले',
    bloodGroup: 'रक्त गट',
    allergies: 'ऍलर्जी आणि इतर समस्या',
    emergencyContacts: 'आपत्कालीन संपर्क',
    addContact: 'नवीन संपर्क जोडा',
    droneTitle: 'ड्रोन टेलीमेट्री',
    droneAltitude: 'उंची',
    droneBattery: 'बॅटरी क्षमता',
    droneSatelites: 'जीपीएस उपग्रह जोडलेले आहेत',
    chatbotTitle: 'सारथी - एआय सरकारी हेल्पडेस्क',
    chatbotWelcome: 'नमस्कार. मी सारथी आहे, रस्ते सुरक्षा एआय मार्गदर्शक. आपला प्रश्न किंवा आपत्कालीन परिस्थिती सांगा.',
    chatbotPrompt: 'सारथीला विचारा (उदा. "जखम कशी बरी करावी?", "हॉस्पिटलचा पत्ता")',
    analysisHeader: 'एआय अपघात अहवाल',
    severityLabel: 'तीव्रता पातळी',
    detectedHazardsLabel: 'धोके आढळले',
    recommendationsLabel: 'शिफारस केलेल्या क्रिया'
  },
  ta: {
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    dashboard: 'டாஷ்போர்டு',
    about: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு',
    sosButton: 'அவசர SOS',
    login: 'உள்நுழை',
    signUp: 'பதிவு செய்',
    govtInitiative: 'இந்திய அரசு முயற்சி',
    ministryLabel: 'சாலைப் போக்குவரத்து மற்றும் நெடுஞ்சாலைத் துறை அமைச்சகம்',
    helplineTitle: 'தேசிய அவசர உதவி எண்கள்',
    policeHelpline: 'காவல்துறை',
    ambulanceHelpline: 'ஆம்புலன்ஸ்',
    highwayHelpline: 'தேசிய நெடுஞ்சாலை ஆணையம்',
    disasterHelpline: 'பேரிடர் மேலாண்மை',
    heroTitle: 'ஒவ்வொரு நொடியும் ஒரு உயிரைக் காக்கும்.',
    heroSubtitle: 'சாலை விபத்துகளுக்கான AI-இயங்கும் அவசர பதில் அமைப்பு. பொன்னான நேரத்தின் (Golden Hour) போது பதில் நேரத்தைக் குறைக்கிறது.',
    tryAI: 'AI உதவியாளரை முயற்சிக்கவும்',
    watchDemo: 'டெமோ பார்க்க',
    sosFlowTitle: 'அவசர SOS செயல்முறை',
    sosFlowSubtitle: 'ஒரே ஒரு தட்டினால் முழு அவசர பதில் நடவடிக்கை தொடங்குகிறது',
    sosStep1Title: 'SOS எச்சரிக்கையைத் தொடங்கு',
    sosStep1Desc: 'SOS பொத்தானைத் தட்டினால் உடனடியாக துல்லியமான ஜிபிஎஸ் ஆயத்தொலைவுகளைப் பெறுகிறது.',
    sosStep2Title: 'SMS மற்றும் தொடர்புகள் ஒளிபரப்பு',
    sosStep2Desc: 'குடும்பத்தினர் மற்றும் பதிவு செய்யப்பட்ட பாதுகாவலர்களுக்கு அவசர எஸ்எம்எஸ் எச்சரிக்கைகளை அனுப்புகிறது.',
    sosStep3Title: 'ஆம்புலன்ஸ் அனுப்புதல்',
    sosStep3Desc: 'அருகிலுள்ள மருத்துவமனைகளுடன் ஒருங்கிணைந்து, ஆம்புலன்ஸ்களை விரைவாக அனுப்புகிறது.',
    sosStep4Title: 'நேரலை வரைபடம்',
    sosStep4Desc: 'அவசரகால வாகனங்களின் நேரடிப் பாதையைக் காட்டுகிறது.',
    aboutTitle: 'சாலை பாதுகாப்பு AI பற்றி',
    aboutSubtitle: 'விபத்தில் சிக்கியவர்களை பொன்னான நேரத்திற்குள் (Golden Hour) அவசர சேவைகளுடன் இணைத்து, உயிர் பிழைப்பதற்கான விகிதத்தை இது கணிசமாக மேம்படுத்துகிறது.',
    value1Title: 'பாதுகாப்பு முதலிடம்',
    value1Desc: 'ஒவ்வொரு அம்சமும் பயனர் பாதுகாப்பை முதன்மையாகக் கொண்டு வடிவமைக்கப்பட்டுள்ளது.',
    value2Title: 'உயிர்களைக் காப்போம்',
    value2Desc: 'இந்தியாவில் சாலை விபத்து இறப்புகளைக் குறைப்பதே எங்கள் நோக்கம்.',
    value3Title: 'மின்னல் வேகம்',
    value3Desc: 'அவசர காலத்தில் சராசரியாக 7 நிமிடங்களுக்குள் உதவி.',
    value4Title: 'சமூக உந்துதல்',
    value4Desc: 'சமூகத்தால், சமூகத்திற்காக உருவாக்கப்பட்டது.',
    impactTitle: 'எங்கள் தாக்கம்',
    livesSaved: 'காக்கப்பட்ட உயிர்கள்',
    hospitals: 'அதிர்ச்சி சிகிச்சை மையங்கள்',
    ambulances: 'இணைக்கப்பட்ட ஆம்புலன்ஸ்கள்',
    cities: 'ஸ்மார்ட் நகரங்கள்',
    contactTitle: 'தொடர்பு கொள்ள',
    contactSubtitle: 'ஏதேனும் கேள்விகள் உள்ளதா? நாங்கள் 24/7 உதவ தயாராக உள்ளோம்',
    email: 'மின்னஞ்சல்',
    emergency: 'அவசர உதவி எண்',
    address: 'முகவரி',
    addressVal: 'டிஜிட்டல் இந்தியா மையம், புது தில்லி',
    nameLabel: 'பெயர்',
    emailLabel: 'மின்னஞ்சல் முகவரி',
    messageLabel: 'செய்தி',
    sendBtn: 'செய்தி அனுப்பவும்',
    firstAidTitle: 'முதலுதவி வழிகாட்டி',
    firstAidSubtitle: 'அவசரகால முதலுதவி மற்றும் சிபிஆர் பயிற்சிகள்',
    cprTitle: 'சிபிஆர் (CPR)',
    cprDesc: 'மருத்துவக் குழு வரும் வரை இரத்த ஓட்டத்தை பராமரிக்க வழிகாட்டி.',
    cprStep1: 'கைகளை நெஞ்சின் நடுவில் வைக்கவும்.',
    cprStep2: 'ஒரு நிமிடத்திற்கு 100-120 முறை வேகத்தில் அழுத்தவும்.',
    cprStep3: 'கீழே உள்ள மெட்ரோனோம் வேகத்தைப் பின்பற்றவும்.',
    metronomeBtnStart: 'சிபிஆர் மெட்ரோனோம் தொடங்குக',
    metronomeBtnStop: 'சிபிஆர் மெட்ரோனோம் நிறுத்துக',
    bleedingTitle: 'இரத்தப்போக்கு கட்டுப்பாடு',
    bleedingDesc: 'கடுமையான இரத்தப்போக்கை உடனடியாக நிறுத்துவதற்கான வழிமுறைகள்.',
    bleedingStep1: 'சுத்தமான துணியால் காயத்தை நேரடியாக அழுத்தவும்.',
    bleedingStep2: 'முடிந்தால் இதய அளவிற்கு மேலே காயத்தை உயர்த்தவும்.',
    bleedingStep3: 'தொடர்ந்து அழுத்தவும்; துணி நனைந்தாலும் மாற்ற வேண்டாம்.',
    mapTitle: 'நேரடி அவசர வரைபடம்',
    mapSubtitle: 'அருகிலுள்ள மருத்துவமனைகள் மற்றும் ஆம்புலன்ஸ்களைக் காட்டும் வரைபடம்',
    satelliteMode: 'செயற்கைக்கோள் வரைபடம்',
    vectorMode: 'இயல்பான வரைபடம்',
    searchServicePlaceholder: 'மருத்துவமனைகளைத் தேடுக...',
    dispatchAmbulanceBtn: 'ஆம்புலன்ஸ் பாதையை உருவகப்படுத்துக',
    hospitalLabel: 'மருத்துவமனை',
    ambulanceLabel: 'ஆம்புலன்ஸ்',
    policeLabel: 'நெடுஞ்சாலை ரோந்து',
    activeHazards: 'சாலை மூடல்கள்',
    reportIncidentBtn: 'விபத்தை பதிவு செய்க',
    loginToReportMsg: 'நேரடியாக விபத்தை பதிவு செய்ய தயவுசெய்து உள்நுழையவும்.',
    dashboardTitle: 'குடிமக்கள் கட்டுப்பாட்டு மையம்',
    dashboardSubtitle: 'உங்கள் மருத்துவ விவரங்கள் மற்றும் அவசர தொடர்புகளை நிர்வகிக்கவும்',
    profileSaved: 'மருத்துவ விவரங்கள் சேமிக்கப்பட்டது',
    bloodGroup: 'இரத்த வகை',
    allergies: 'ஒவ்வாமைகள் மற்றும் பிற பிரச்சினைகள்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    addContact: 'புதிய தொடர்பைச் சேர்க்கவும்',
    droneTitle: 'ட்ரோன் டெலிமெட்ரி',
    droneAltitude: 'உயரம்',
    droneBattery: 'பேட்டரி அளவு',
    droneSatelites: 'இணைக்கப்பட்ட ஜிபிஎஸ் செயற்கைக்கோள்கள்',
    chatbotTitle: 'சாரதி - AI அரசு உதவி மையம்',
    chatbotWelcome: 'வணக்கம். நான் சாரதி, சாலை பாதுகாப்பு AI உதவியாளர். உங்கள் அவசரநிலை அல்லது கேள்வியைக் கூறவும்.',
    chatbotPrompt: 'சாரதியிடம் கேளுங்கள் (எ.கா. "தீக்காயத்திற்கு என்ன செய்வது?")',
    analysisHeader: 'AI விபத்து பகுப்பாய்வு',
    severityLabel: 'விபத்து தீவிரம்',
    detectedHazardsLabel: 'கண்டறியப்பட்ட ஆபத்துகள்',
    recommendationsLabel: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்'
  },
  te: {
    home: 'హోమ్',
    features: 'ఫీచర్లు',
    dashboard: 'డాష్‌బోర్డ్',
    about: 'మా గురించి',
    contact: 'సంప్రదించండి',
    sosButton: 'అత్యవసర SOS',
    login: 'లాగిన్',
    signUp: 'సైన్ అప్',
    govtInitiative: 'భారత ప్రభుత్వ చొరవ',
    ministryLabel: 'రహదారి రవాణా మరియు రహదారుల మంత్రిత్వ శాఖ',
    helplineTitle: 'జాతీయ అత్యవసర టోల్-ఫ్రీ హెల్ప్‌లైన్లు',
    policeHelpline: 'పోలీస్',
    ambulanceHelpline: 'అంబులెన్స్',
    highwayHelpline: 'జాతీయ రహదారుల సంస్థ',
    disasterHelpline: 'విపత్తు నిర్వహణ',
    heroTitle: 'ప్రతి సెకను ఒక ప్రాణాన్ని కాపాడుతుంది.',
    heroSubtitle: 'రహదారి ప్రమాదాల కోసం AI-ఆధారిత అత్యవసర ప్రతిస్పందన వ్యవస్థ. గోల్డెన్ అవర్ (Golden Hour) సమయంలో ప్రతిస్పందన సమయాన్ని తగ్గిస్తుంది.',
    tryAI: 'AI సహాయకుడిని ప్రయత్నించండి',
    watchDemo: 'డెమో చూడండి',
    sosFlowTitle: 'అత్యవసర SOS ప్రక్రియ',
    sosFlowSubtitle: 'ఒకసారి నొక్కితే పూర్తి అత్యవసర ప్రతిస్పందన చర్య ప్రారంభమవుతుంది',
    sosStep1Title: 'SOS హెచ్చరికను ప్రారంభించండి',
    sosStep1Desc: 'SOS బటన్ నొక్కగానే ఖచ్చితమైన జీపీఎస్ స్థానాన్ని గుర్తిస్తుంది.',
    sosStep2Title: 'SMS మరియు కాంటాక్ట్స్ బ్రాడ్‌కాస్ట్',
    sosStep2Desc: 'కుటుంబ సభ్యులకు మరియు రక్షకులకు అత్యవసర ఎస్ఎంఎస్ హెచ్చరికలను పంపుతుంది.',
    sosStep3Title: 'అంబులెన్స్ పంపడం',
    sosStep3Desc: 'సమీప ఆసుపత్రులతో సమన్వయం చేసుకుని, త్వరగా అంబులెన్స్‌లను పంపుతుంది.',
    sosStep4Title: 'లైవ్ మ్యాప్',
    sosStep4Desc: 'అత్యవసర వాహనాల మార్గాన్ని ప్రత్యక్షంగా చూపుతుంది.',
    aboutTitle: 'రోడ్ సేఫ్టీ AI గురించి',
    aboutSubtitle: 'రోడ్డు ప్రమాద బాధితులను గోల్డెన్ అవర్ (Golden Hour) లో అత్యవసర సేవలతో అనుసంధానించడం ద్వారా ప్రాణాలను కాపాడుతుంది.',
    value1Title: 'భద్రత ప్రధమం',
    value1Desc: 'ప్రతి ఫీచర్ వినియోగదారు భద్రతను దృష్టిలో ఉంచుకుని రూపొందించబడింది.',
    value2Title: 'ప్రాణాలు కాపాడండి',
    value2Desc: 'భారతదేశంలో రోడ్డు ప్రమాదాల మరణాలను తగ్గించడమే మా లక్ష్యం.',
    value3Title: 'మెరుపు వేగం',
    value3Desc: 'అత్యవసర పరిస్థితుల్లో సగటున 7 నిమిషాల్లో సహాయం లభిస్తుంది.',
    value4Title: 'కమ్యూనిటీ ఆధారిత',
    value4Desc: 'కమ్యూనిటీ కోసం, కమ్యూనిటీ ద్వారా నిర్మించబడింది.',
    impactTitle: 'మా ప్రభావం',
    livesSaved: 'కాపాడిన ప్రాణాలు',
    hospitals: 'ట్రామా కేర్ సెంటర్లు',
    ambulances: 'కనెక్ట్ చేయబడిన అంబులెన్సులు',
    cities: 'స్మార్ట్ నగరాలు',
    contactTitle: 'సంప్రదించండి',
    contactSubtitle: 'ఏవైనా ప్రశ్నలు ఉన్నాయా? మేము 24/7 సహాయం చేయడానికి సిద్ధంగా ఉన్నాము',
    email: 'ఈమెయిల్',
    emergency: 'అత్యవసర హెల్ప్‌లైన్',
    address: 'చిరునామా',
    addressVal: 'డిజిటల్ ఇండియా కేంద్రం, న్యూఢిల్లీ',
    nameLabel: 'పేరు',
    emailLabel: 'ఈమెయిల్ చిరునామా',
    messageLabel: 'సందేశం',
    sendBtn: 'సందేశం పంపండి',
    firstAidTitle: 'ప్రథమ చికిత్స మార్గదర్శి',
    firstAidSubtitle: 'అత్యవసర ప్రథమ చికిత్స మరియు సిపిఆర్ శిక్షణ',
    cprTitle: 'సిపిఆర్ (CPR)',
    cprDesc: 'వైద్య బృందం వచ్చే వరకు రక్త ప్రసరణను కొనసాగించడానికి మార్గదర్శి.',
    cprStep1: 'చేతులను ఛాతీ మధ్యలో ఉంచండి.',
    cprStep2: 'నిమిషానికి 100-120 సార్లు వేగంతో నొక్కండి.',
    cprStep3: 'క్రింది మెట్రోనొమ్ వేగాన్ని అనుసరించండి.',
    metronomeBtnStart: 'సిపిఆర్ మెట్రోనొమ్ ప్రారంభించు',
    metronomeBtnStop: 'సిపిఆర్ మెట్రోనొమ్ ఆపివేయి',
    bleedingTitle: 'రక్తస్రావం నియంత్రణ',
    bleedingDesc: 'తీవ్రమైన రక్తస్రావాన్ని వెంటనే ఆపడానికి సూచనలు.',
    bleedingStep1: 'శుభ్రమైన గుడ్డతో గాయాన్ని నేరుగా నొక్కండి.',
    bleedingStep2: 'గాయపడిన భాగాన్ని గుండె స్థాయి కంటే ఎత్తులో ఉంచండి.',
    bleedingStep3: 'ఒత్తిడిని కొనసాగించండి; గుడ్డ తడిసినా తీసివేయవద్దు.',
    mapTitle: 'ప్రత్యక్ష అత్యవసర మ్యాప్',
    mapSubtitle: 'సమీప ఆసుపత్రులు మరియు అంబులెన్సులను చూపించే మ్యాప్',
    satelliteMode: 'శాటిలైట్ మ్యాప్',
    vectorMode: 'సాధారణ మ్యాప్',
    searchServicePlaceholder: 'ఆసుపత్రుల కోసం శోధించండి...',
    dispatchAmbulanceBtn: 'అంబులెన్స్ మార్గాన్ని అనుకరించండి',
    hospitalLabel: 'ఆసుపత్రి',
    ambulanceLabel: 'అంబులెన్స్',
    policeLabel: 'హైవే పెట్రోలింగ్',
    activeHazards: 'రహదారి మూసివేతలు',
    reportIncidentBtn: 'ప్రమాదాన్ని నమోదు చేయండి',
    loginToReportMsg: 'నేరుగా ప్రమాదాన్ని నమోదు చేయడానికి దయచేసి లాగిన్ అవ్వండి.',
    dashboardTitle: 'పౌరుల నియంత్రణ కేంద్రం',
    dashboardSubtitle: 'మీ వైద్య వివరాలు మరియు అత్యవసర కాంటాక్ట్‌లను నిర్వహించండి',
    profileSaved: 'వైద్య వివరాలు సేవ్ చేయబడ్డాయి',
    bloodGroup: 'రక్త రకం',
    allergies: 'అలెర్జీలు మరియు ఇతర సమస్యలు',
    emergencyContacts: 'అత్యవసర కాంటాక్ట్‌లు',
    addContact: 'కొత్త కాంటాక్ట్‌ని జోడించండి',
    droneTitle: 'డ్రోన్ టెలిమెట్రీ',
    droneAltitude: 'ఎత్తు',
    droneBattery: 'బ్యాటరీ స్థాయి',
    droneSatelites: 'కనెక్ట్ చేయబడిన జీపీఎస్ శాటిలైట్లు',
    chatbotTitle: 'సారథి - AI ప్రభుత్వ సహాయ కేంద్రం',
    chatbotWelcome: 'నమస్కారం. నేను సారథిని, రోడ్డు భద్రతా AI సహాయకుడిని. మీ అత్యవసర పరిస్థితి లేదా ప్రశ్నను తెలపండి.',
    chatbotPrompt: 'సారథిని అడగండి (ఉదా. "కాలిపోయినప్పుడు ఏం చేయాలి?")',
    analysisHeader: 'AI ప్రమాద విశ్లేషణ',
    severityLabel: 'ప్రమాద తీవ్రత',
    detectedHazardsLabel: 'గుర్తించిన ప్రమాదాలు',
    recommendationsLabel: 'సిఫార్సు చేసిన చర్యలు'
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    sosButton: 'ತುರ್ತು SOS',
    login: 'ಲಾಗಿನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    govtInitiative: 'ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮ',
    ministryLabel: 'ರಸ್ತೆ ಸಾರಿಗೆ ಮತ್ತು ಹೆದ್ದಾರಿ ಸಚಿವಾಲಯ',
    helplineTitle: 'ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಹಾಯವಾಣಿಗಳು',
    policeHelpline: 'ಪೊಲೀಸ್',
    ambulanceHelpline: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    highwayHelpline: 'ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ ಪ್ರಾಧಿಕಾರ',
    disasterHelpline: 'ವಿಪತ್ತು ನಿರ್ವಹಣೆ',
    heroTitle: 'ಪ್ರತಿ ಸೆಕೆಂಡ್ ಒಂದು ಜೀವವನ್ನು ಉಳಿಸುತ್ತದೆ.',
    heroSubtitle: 'ರಸ್ತೆ ಅಪಘಾತಗಳಿಗಾಗಿ AI-ಚಾಲಿತ ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ವ್ಯವಸ್ಥೆ. ಗೋಲ್ಡನ್ ಅವರ್ (Golden Hour) ಸಮಯದಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.',
    tryAI: 'AI ಸಹಾಯಕರನ್ನು ಪ್ರಯತ್ನಿಸಿ',
    watchDemo: 'ಡೆಮೊ ವೀಕ್ಷಿಸಿ',
    sosFlowTitle: 'ತುರ್ತು SOS ಪ್ರಕ್ರಿಯೆ',
    sosFlowSubtitle: 'ಒಂದು ಟ್ಯಾಪ್ ಮೂಲಕ ಸಂಪೂರ್ಣ ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರಕ್ರಿಯೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ',
    sosStep1Title: 'SOS ಎಚ್ಚರಿಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    sosStep1Desc: 'SOS ಬಟನ್ ಒತ್ತಿದ ತಕ್ಷಣ ನಿಖರವಾದ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಗುರುತಿಸುತ್ತದೆ.',
    sosStep2Title: 'SMS ಮತ್ತು ಸಂಪರ್ಕಗಳ ಪ್ರಸಾರ',
    sosStep2Desc: 'ಕುಟುಂಬ ಸದಸ್ಯರಿಗೆ ಮತ್ತು ಪೋಷಕರಿಗೆ ತುರ್ತು ಎಸ್‌ಎಂಎಸ್ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಕಳುಹಿಸುತ್ತದೆ.',
    sosStep3Title: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ರವಾನೆ',
    sosStep3Desc: 'ಸಮೀಪದ ಆಸ್ಪತ್ರೆಗಳೊಂದಿಗೆ ಸಮನ್ವಯ ಸಾಧಿಸಿ, ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳನ್ನು ತ್ವರಿತವಾಗಿ ಕಳುಹಿಸುತ್ತದೆ.',
    sosStep4Title: 'ಲೈವ್ ಮ್ಯಾಪ್',
    sosStep4Desc: 'ತುರ್ತು ವಾಹನಗಳ ಮಾರ್ಗವನ್ನು ನೇರವಾಗಿ ತೋರಿಸುತ್ತದೆ.',
    aboutTitle: 'ರಸ್ತೆ ಸುರಕ್ಷತೆ AI ಬಗ್ಗೆ',
    aboutSubtitle: 'ರಸ್ತೆ ಅಪಘಾತದ ಬಲಿಪಶುಗಳನ್ನು ಗೋಲ್ಡನ್ ಅವರ್ (Golden Hour) ನಲ್ಲಿ ತುರ್ತು ಸೇವೆಗಳೊಂದಿಗೆ ಜೋಡಿಸುವ ಮೂಲಕ ಜೀವವನ್ನು ಉಳಿಸುತ್ತದೆ.',
    value1Title: 'ಸುರಕ್ಷತೆ ಮೊದಲು',
    value1Desc: 'ಬಳಕೆದಾರರ ಸುರಕ್ಷತೆಯನ್ನು ಗಮನದಲ್ಲಿಟ್ಟುಕೊಂಡು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಪ್ರತಿ ವೈಶಿಷ್ಟ್ಯ.',
    value2Title: 'ಜೀವ ಉಳಿಸಿ',
    value2Desc: 'ಭಾರತದಾದ್ಯಂತ ರಸ್ತೆ ಅಪಘಾತದ ಸಾವುಗಳನ್ನು ಕಡಿಮೆ ಮಾಡುವುದು ನಮ್ಮ ಗುರಿ.',
    value3Title: 'ಮಿಂಚಿನ ವೇಗ',
    value3Desc: 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಕೇವಲ 7 ನಿಮಿಷಗಳಲ್ಲಿ ಸಹಾಯ.',
    value4Title: 'ಸಮುದಾಯ ಆಧಾರಿತ',
    value4Desc: 'ಸಮುದಾಯಕ್ಕಾಗಿ, ಸಮುದಾಯದ ಮೂಲಕ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    impactTitle: 'ನಮ್ಮ ಪ್ರಭಾವ',
    livesSaved: 'ಉಳಿಸಿದ ಜೀವಗಳು',
    hospitals: 'ಟ್ರಾಮಾ ಕೇರ್ ಕೇಂದ್ರಗಳು',
    ambulances: 'ಸಂಪರ್ಕಿತ ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳು',
    cities: 'ಸ್ಮಾರ್ಟ್ ನಗರಗಳು',
    contactTitle: 'ಸಂಪರ್ಕಿಸಿ',
    contactSubtitle: 'ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿವೆಯೇ? ನಾವು 24/7 ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೇವೆ',
    email: 'ಇಮೇಲ್',
    emergency: 'ತುರ್ತು ಸಹಾಯವಾಣಿ',
    address: 'ವಿಳಾಸ',
    addressVal: 'ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ ಕೇಂದ್ರ, ನವದೆಹಲಿ',
    nameLabel: 'ಹೆಸರು',
    emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
    messageLabel: 'ಸಂದೇಶ',
    sendBtn: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    firstAidTitle: 'ಪ್ರಥಮ ಚಿಕಿತ್ಸಾ ಮಾರ್ಗದರ್ಶಿ',
    firstAidSubtitle: 'ತುರ್ತು ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಮತ್ತು ಸಿಪಿಆರ್ ತರಬೇತಿ',
    cprTitle: 'ಸಿಪಿಆರ್ (CPR)',
    cprDesc: 'ವೈದ್ಯಕೀಯ ತಂಡ ಬರುವವರೆಗೆ ರಕ್ತ ಪರಿಚಲನೆ ಕಾಪಾಡಿಕೊಳ್ಳಲು ಮಾರ್ಗದರ್ಶಿ.',
    cprStep1: 'ಕೈಗಳನ್ನು ಎದೆಯ ಮಧ್ಯದಲ್ಲಿ ಇರಿಸಿ.',
    cprStep2: 'ನಿಮಿಷಕ್ಕೆ 100-120 ಬಾರಿ ವೇಗದಲ್ಲಿ ಒತ್ತಿರಿ.',
    cprStep3: 'ಕೆಳಗಿನ ಮೆಟ್ರೋನೋಮ್ ವೇಗವನ್ನು ಅನುಸರಿಸಿ.',
    metronomeBtnStart: 'ಸಿಪಿಆರ್ ಮೆಟ್ರೋನೋಮ್ ಪ್ರಾರಂಭಿಸಿ',
    metronomeBtnStop: 'ಸಿಪಿಆರ್ ಮೆಟ್ರೋನೋಮ್ ನಿಲ್ಲಿಸಿ',
    bleedingTitle: 'ರಕ್ತಸ್ರಾವ ನಿಯಂತ್ರಣ',
    bleedingDesc: 'ತೀವ್ರ ರಕ್ತಸ್ರಾವವನ್ನು ತಕ್ಷಣ ನಿಲ್ಲಿಸಲು ಸೂಚನೆಗಳು.',
    bleedingStep1: 'ಶುದ್ಧ ಬಟ್ಟೆಯಿಂದ ಗಾಯವನ್ನು ನೇರವಾಗಿ ಒತ್ತಿರಿ.',
    bleedingStep2: 'ಗಾಯಗೊಂಡ ಭಾಗವನ್ನು ಹೃದಯದ ಮಟ್ಟಕ್ಕಿಂತ ಎತ್ತರದಲ್ಲಿರಿಸಿ.',
    bleedingStep3: 'ಒತ್ತಡವನ್ನು ಮುಂದುವರಿಸಿ; ಬಟ್ಟೆ ಒದ್ದೆಯಾದರೂ ತೆಗೆಯಬೇಡಿ.',
    mapTitle: 'ಲೈವ್ ತುರ್ತು ಮ್ಯಾಪ್',
    mapSubtitle: 'ಸಮೀಪದ ಆಸ್ಪತ್ರೆಗಳು ಮತ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳನ್ನು ತೋರಿಸುವ ಮ್ಯಾಪ್',
    satelliteMode: 'ಸ್ಯಾಟಲೈಟ್ ಮ್ಯಾಪ್',
    vectorMode: 'ಸಾಮಾನ್ಯ ಮ್ಯಾಪ್',
    searchServicePlaceholder: 'ಆಸ್ಪತ್ರೆಗಳಿಗಾಗಿ ಹುಡುಕಿ...',
    dispatchAmbulanceBtn: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ಮಾರ್ಗವನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ',
    hospitalLabel: 'ಆಸ್ಪತ್ರೆ',
    ambulanceLabel: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    policeLabel: 'ಹೆದ್ದಾರಿ ಗಸ್ತು',
    activeHazards: 'ರಸ್ತೆ ಮುಚ್ಚುವಿಕೆಗಳು',
    reportIncidentBtn: 'ಅಪಘಾತವನ್ನು ವರದಿ ಮಾಡಿ',
    loginToReportMsg: 'ನೇರವಾಗಿ ಅಪಘಾತವನ್ನು ವರದಿ ಮಾಡಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.',
    dashboardTitle: 'ನಾಗರಿಕ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ',
    dashboardSubtitle: 'ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ವಿವರಗಳು ಮತ್ತು ತುರ್ತು ಸಂಪರ್ಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    profileSaved: 'ವೈದ್ಯಕೀಯ ವಿವರಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
    bloodGroup: 'ರಕ್ತದ ಗುಂಪು',
    allergies: 'ಅಲರ್ಜಿಗಳು ಮತ್ತು ಇತರ ಸಮಸ್ಯೆಗಳು',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    addContact: 'ಹೊಸ ಸಂಪರ್ಕವನ್ನು ಸೇರಿಸಿ',
    droneTitle: 'ಡ್ರೋನ್ ಟೆಲಿಮೆಟ್ರಿ',
    droneAltitude: 'ಎತ್ತರ',
    droneBattery: 'ಬ್ಯಾಟರಿ ಮಟ್ಟ',
    droneSatelites: 'ಸಂಪರ್ಕಿತ ಜಿಪಿಎಸ್ ಉಪಗ್ರಹಗಳು',
    chatbotTitle: 'ಸಾರಥಿ - AI ಸರ್ಕಾರಿ ಸಹಾಯ ಕೇಂದ್ರ',
    chatbotWelcome: 'ನಮಸ್ಕಾರ. ನಾನು ಸಾರಥಿ, ರಸ್ತೆ ಸುರಕ್ಷತೆ AI ಸಹಾಯಕ. ನಿಮ್ಮ ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಅಥವಾ ಪ್ರಶ್ನೆಯನ್ನು ತಿಳಿಸಿ.',
    chatbotPrompt: 'ಸಾರಥಿಯನ್ನು ಕೇಳಿ (ಉದಾ. "ಸುಟ್ಟ ಗಾಯಕ್ಕೆ ಏನು ಮಾಡಬೇಕು?")',
    analysisHeader: 'AI ಅಪಘಾತ ವಿಶ್ಲೇಷಣೆ',
    severityLabel: 'ಅಪಘಾತದ ತೀವ್ರತೆ',
    detectedHazardsLabel: 'ಗುರುತಿಸಲಾದ ಅಪಾಯಗಳು',
    recommendationsLabel: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು'
  },
  es: {
    home: 'Inicio',
    features: 'Características',
    dashboard: 'Panel de Control',
    about: 'Nosotros',
    contact: 'Contacto',
    sosButton: 'S.O.S. de Emergencia',
    login: 'Iniciar Sesión',
    signUp: 'Registrarse',
    govtInitiative: 'Iniciativa del Gobierno de la India',
    ministryLabel: 'Ministerio de Transporte por Carretera y Autopistas',
    helplineTitle: 'Líneas de Ayuda de Emergencia Nacional Gratuitas',
    policeHelpline: 'Policía',
    ambulanceHelpline: 'Ambulancia',
    highwayHelpline: 'Autoridad Nacional de Autopistas',
    disasterHelpline: 'Gestión de Desastres',
    heroTitle: 'Cada Segundo Salva una Vida.',
    heroSubtitle: 'Sistema de respuesta a emergencias para accidentes viales impulsado por IA. Reducción del tiempo de respuesta durante la Hora Dorada.',
    tryAI: 'Probar Asistente de IA',
    watchDemo: 'Ver Demostración',
    sosFlowTitle: 'Flujo de Emergencia SOS',
    sosFlowSubtitle: 'La activación con un solo toque activa una secuencia completa de respuesta a emergencias',
    sosStep1Title: 'Activar Alerta SOS',
    sosStep1Desc: 'El botón SOS de un toque captura inmediatamente las coordenadas GPS precisas y los perfiles médicos.',
    sosStep2Title: 'Difusión de SMS y Contactos',
    sosStep2Desc: 'Envía alertas de SMS de emergencia con enlaces de mapas en vivo a familiares y tutores registrados.',
    sosStep3Title: 'Despacho de Ambulancia',
    sosStep3Desc: 'Coordina con los hospitales de traumatología más cercanos, despachando paramédicos usando rutas inteligentes.',
    sosStep4Title: 'Mapa de Despacho en Vivo',
    sosStep4Desc: 'Muestra navegación de ruta en tiempo real para vehículos médicos entrantes.',
    aboutTitle: 'Acerca de RoadSOS AI',
    aboutSubtitle: 'RoadSOS AI es una iniciativa del Gobierno de la India para aprovechar la inteligencia artificial para la seguridad vial y la respuesta a emergencias. Nuestra plataforma conecta a las víctimas de accidentes con los servicios de emergencia dentro de la Hora Dorada crítica, mejorando significativamente las tasas de supervivencia.',
    value1Title: 'Seguridad Primero',
    value1Desc: 'Cada función diseñada con la seguridad del usuario como máxima prioridad.',
    value2Title: 'Salvar Vidas',
    value2Desc: 'Nuestra misión es reducir las muertes por accidentes de tránsito en toda la India.',
    value3Title: 'Rápido como el Rayo',
    value3Desc: 'Tiempo de respuesta promedio de solo 7 minutos durante emergencias.',
    value4Title: 'Impulsado por la Comunidad',
    value4Desc: 'Construido por la comunidad, para la comunidad.',
    impactTitle: 'Nuestro Impacto',
    livesSaved: 'Vidas Salvadas',
    hospitals: 'Centros de Trauma',
    ambulances: 'Ambulancias Conectadas',
    cities: 'Ciudades Inteligentes',
    contactTitle: 'Contáctenos',
    contactSubtitle: '¿Tiene preguntas? Estamos aquí para ayudar las 24 horas, los 7 días de la semana',
    email: 'Correo Electrónico',
    emergency: 'Línea de Ayuda de Emergencia',
    address: 'Dirección',
    addressVal: 'Centro Digital India, Nueva Delhi',
    nameLabel: 'Nombre',
    emailLabel: 'Correo Electrónico',
    messageLabel: 'Mensaje',
    sendBtn: 'Enviar Mensaje',
    firstAidTitle: 'Guía de Primeros Auxilios',
    firstAidSubtitle: 'Instrucciones interactivas y soporte de RCP durante emergencias',
    cprTitle: 'Reanimación Cardiopulmonar (RCP)',
    cprDesc: 'Guía para que los transeúntes mantengan la sangre circulando hasta que lleguen los paramédicos.',
    cprStep1: 'Coloque las manos en el centro del pecho.',
    cprStep2: 'Empuje fuerte y rápido a una velocidad de 100 a 120 compresiones por minuto.',
    cprStep3: 'Siga el ritmo del metrónomo a continuación.',
    metronomeBtnStart: 'Iniciar metrónomo de RCP',
    metronomeBtnStop: 'Detener metrónomo de RCP',
    bleedingTitle: 'Manejo del Sangrado',
    bleedingDesc: 'Pasos inmediatos para controlar hemorragias graves.',
    bleedingStep1: 'Aplique presión directa con un paño limpio o una venda.',
    bleedingStep2: 'Eleve la herida por encima del nivel del corazón si es posible.',
    bleedingStep3: 'Mantenga la presión; no retire el paño si está empapado.',
    mapTitle: 'Mapa de Emergencia en Vivo',
    mapSubtitle: 'Cuadrícula en tiempo real que muestra los centros de trauma cercanos y los despachos de ambulancias',
    satelliteMode: 'Vista de satélite',
    vectorMode: 'Vista de mapa estándar',
    searchServicePlaceholder: 'Buscar hospitales o ambulancias...',
    dispatchAmbulanceBtn: 'Simular Ruta de Despacho',
    hospitalLabel: 'Hospital de Trauma',
    ambulanceLabel: 'Ambulancia Paramédica',
    policeLabel: 'Escuadrón de Patrulla',
    activeHazards: 'Cierres de carreteras',
    reportIncidentBtn: 'Registrar Informe de Accidente',
    loginToReportMsg: 'Inicie sesión para enviar informes de accidentes de tráfico directamente a los despachadores.',
    dashboardTitle: 'Centro de Control Ciudadano',
    dashboardSubtitle: 'Administre su información médica y contactos de emergencia',
    profileSaved: 'Perfil médico guardado correctamente',
    bloodGroup: 'Grupo Sanguíneo',
    allergies: 'Alergias y contraindicaciones',
    emergencyContacts: 'Contactos de Emergencia',
    addContact: 'Agregar Nuevo Contacto',
    droneTitle: 'Telemetría de Dron',
    droneAltitude: 'Altitud',
    droneBattery: 'Batería',
    droneSatelites: 'Satélites GPS Conectados',
    chatbotTitle: 'Sarthi - Asistencia de IA del Gobierno',
    chatbotWelcome: 'Saludos. Soy Sarthi, su guía oficial de IA para la seguridad vial. Ingrese su emergencia o consulta.',
    chatbotPrompt: 'Pregunte a Sarthi (ej. "¿Cómo tratar una quemadura?")',
    analysisHeader: 'Informe de Análisis de Daños por IA',
    severityLabel: 'Severidad del Daño',
    detectedHazardsLabel: 'Peligros Identificados',
    recommendationsLabel: 'Acciones Recomendadas'
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>('en')

  // Read language configuration on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('language')
      if (
        stored === 'hi' ||
        stored === 'en' ||
        stored === 'mr' ||
        stored === 'ta' ||
        stored === 'te' ||
        stored === 'kn' ||
        stored === 'es'
      ) {
        setLanguage(stored as LanguageCode)
      }
    }
  }, [])

  const setLanguageAndStore = (lang: LanguageCode) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageAndStore, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
